
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Image image1;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.RadioButton hardRadioBtn;
	
	private global::Gtk.RadioButton intRadioBtn;
	
	private global::Gtk.RadioButton ezRadioBtn;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.Button aboutBtn;
	
	private global::Gtk.Image image2;
	
	private global::Gtk.Button button4;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Rhythm Jumper");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("RhythmJumperLinux.images.RhythmJumper_64BitIcon.ico");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("RhythmJumperLinux.images.RhythmJumper_Background_MainMenu.png");
		this.fixed1.Add (this.image1);
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("<span weight=\"bold\" color=\"white\" size=\"20pt\">Rhythm Jumper</span>");
		this.label6.UseMarkup = true;
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w2.X = 124;
		w2.Y = 5;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("<span weight=\"bold\" color=\"white\" size=\"14pt\">Linux Edition</span>");
		this.label7.UseMarkup = true;
		this.fixed1.Add (this.label7);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
		w3.X = 179;
		w3.Y = 36;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Let\'s Go!");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w4.X = 33;
		w4.Y = 251;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("    Exit    ");
		this.fixed1.Add (this.button2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button2]));
		w5.X = 403;
		w5.Y = 251;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"white\">Hard</span>");
		this.label8.UseMarkup = true;
		this.fixed1.Add (this.label8);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
		w6.X = 74;
		w6.Y = 140;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"white\">Intermediate</span>");
		this.label9.UseMarkup = true;
		this.fixed1.Add (this.label9);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
		w7.X = 71;
		w7.Y = 163;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"white\">EZ</span>");
		this.label10.UseMarkup = true;
		this.fixed1.Add (this.label10);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label10]));
		w8.X = 70;
		w8.Y = 187;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hardRadioBtn = new global::Gtk.RadioButton ("");
		this.hardRadioBtn.CanFocus = true;
		this.hardRadioBtn.Name = "hardRadioBtn";
		this.hardRadioBtn.DrawIndicator = true;
		this.hardRadioBtn.UseUnderline = true;
		this.hardRadioBtn.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.hardRadioBtn);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.hardRadioBtn]));
		w9.X = 37;
		w9.Y = 136;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.intRadioBtn = new global::Gtk.RadioButton ("");
		this.intRadioBtn.CanFocus = true;
		this.intRadioBtn.Name = "intRadioBtn";
		this.intRadioBtn.DrawIndicator = true;
		this.intRadioBtn.UseUnderline = true;
		this.intRadioBtn.Group = this.hardRadioBtn.Group;
		this.fixed1.Add (this.intRadioBtn);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.intRadioBtn]));
		w10.X = 37;
		w10.Y = 160;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ezRadioBtn = new global::Gtk.RadioButton ("");
		this.ezRadioBtn.CanFocus = true;
		this.ezRadioBtn.Name = "ezRadioBtn";
		this.ezRadioBtn.DrawIndicator = true;
		this.ezRadioBtn.UseUnderline = true;
		this.ezRadioBtn.Group = this.hardRadioBtn.Group;
		this.fixed1.Add (this.ezRadioBtn);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ezRadioBtn]));
		w11.X = 36;
		w11.Y = 184;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"white\">\nSPACE to jump.\nPress Ctrl+E while in-game to quit game.\nIf y" +
		"ou land on an obstacle, you have to start over.\nSome obstacles are tricks and do" +
		"n\'t go all the way ;)\n</span>");
		this.label11.UseMarkup = true;
		this.label11.Justify = ((global::Gtk.Justification)(1));
		this.fixed1.Add (this.label11);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label11]));
		w12.X = 149;
		w12.Y = 125;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.aboutBtn = new global::Gtk.Button ();
		this.aboutBtn.CanFocus = true;
		this.aboutBtn.Name = "aboutBtn";
		this.aboutBtn.UseUnderline = true;
		this.aboutBtn.Label = global::Mono.Unix.Catalog.GetString ("   About   ");
		this.fixed1.Add (this.aboutBtn);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.aboutBtn]));
		w13.X = 217;
		w13.Y = 250;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image2 = new global::Gtk.Image ();
		this.image2.Name = "image2";
		this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("RhythmJumperLinux.images.RJ_Person.png");
		this.fixed1.Add (this.image2);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.image2]));
		w14.X = 391;
		w14.Y = 57;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("?");
		this.fixed1.Add (this.button4);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button4]));
		w15.X = 458;
		w15.Y = 77;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 500;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
	}
}
