'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RhythmJumper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # Easter Egg Hints!
        '''
        '''## Easter Egg Hint #1
        '''Have you played Contra before or heard of it?
        '''
        '''## Easter Egg Hint #2
        '''The quick brown dog jumps over the lazy ___.
        '''
        '''## Easter Egg Hint #3
        '''The app doesn&apos;t give you a good hint on purpose. Well, glad you came here!
        '''  
        '''  It&apos;s pretty hard to solve, so I&apos;ll give you some hints. ;)
        '''  
        '''  - Key #1
        '''  The fourth key in Easter Egg #1.
        '''  
        '''  - Key #2
        '''  The opposite of Key #1.
        '''  
        '''  - Key #3
        '''  This game did not use the following programming language or platform...
        '''
        '''    w. Visual B [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EasterEggHints_md() As String
            Get
                Return ResourceManager.GetString("EasterEggHints_md", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property FinalBattle_INT() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("FinalBattle_INT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Kurorak_Artha_HRD() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Kurorak_Artha_HRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NOTE (PLEASE READ THE FOLLOWING TEXT AS IT APPLIES TO YOUR USE OF SPECIFIC FILES FOUND IN THIS REPOSITORY THAT HAVE BEEN REDISTRIBUTED FROM OTHER SOURCES):
        '''
        '''The following license (Mozilla Public License Version 2.0) applies to all files in this repository except for the following: https://github.com/siliconninja/RhythmJumper/blob/master/RhythmJumper/RhythmJumper/Resources/TimeLeap_EZ.wav (referred to as &quot;TimeLeap_EZ.wav&quot;), https://github.com/siliconninja/RhythmJumper/blob/master/RhythmJumper/RhythmJumper/Re [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LICENSE() As String
            Get
                Return ResourceManager.GetString("LICENSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NOTE (PLEASE READ THE FOLLOWING TEXT AS IT APPLIES TO YOUR USE OF SPECIFIC FILES FOUND IN THIS REPOSITORY THAT HAVE BEEN REDISTRIBUTED FROM OTHER SOURCES):
        '''
        '''The following license (Mozilla Public License Version 2.0) applies to all files in this repository except for the following:
        '''https://github.com/siliconninja/RhythmJumper/blob/master/RhythmJumper/RhythmJumper/Resources/FinalBattle_INT-2.wav (referred to as &quot;FinalBattle_INT-2.wav&quot;),
        '''and https://github.com/siliconninja/RhythmJumper/blob/master/RhythmJumper [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LICENSE_SONGS() As String
            Get
                Return ResourceManager.GetString("LICENSE_SONGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RhythmJumper_64BitIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RhythmJumper_64BitIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RhythmJumper_64BitIcon1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RhythmJumper_64BitIcon1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RhythmJumper_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RhythmJumper_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RhythmJumper_Background_MainMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RhythmJumper_Background_MainMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RJ_Person() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RJ_Person", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
